# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flushing-flash}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{PeterWong}]
  s.date = %q{2011-11-10}
  s.description = %q{To provide helper methods for handling rails flash messages.}
  s.email = %q{peter@peterwongpp.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "flushing-flash.gemspec",
    "lib/flushing-flash.rb",
    "lib/flushing-flash/action_controller_methods.rb",
    "lib/flushing-flash/action_view_methods.rb",
    "lib/flushing-flash/version.rb",
    "test/dummy-with-devise/.gitignore",
    "test/dummy-with-devise/Gemfile",
    "test/dummy-with-devise/Gemfile.lock",
    "test/dummy-with-devise/README",
    "test/dummy-with-devise/Rakefile",
    "test/dummy-with-devise/app/assets/images/rails.png",
    "test/dummy-with-devise/app/assets/javascripts/application.js",
    "test/dummy-with-devise/app/assets/javascripts/home.js.coffee",
    "test/dummy-with-devise/app/assets/stylesheets/application.css",
    "test/dummy-with-devise/app/assets/stylesheets/home.css.scss",
    "test/dummy-with-devise/app/controllers/application_controller.rb",
    "test/dummy-with-devise/app/controllers/home_controller.rb",
    "test/dummy-with-devise/app/helpers/application_helper.rb",
    "test/dummy-with-devise/app/helpers/home_helper.rb",
    "test/dummy-with-devise/app/mailers/.gitkeep",
    "test/dummy-with-devise/app/models/.gitkeep",
    "test/dummy-with-devise/app/models/user.rb",
    "test/dummy-with-devise/app/views/home/index.html.erb",
    "test/dummy-with-devise/app/views/layouts/application.html.erb",
    "test/dummy-with-devise/config.ru",
    "test/dummy-with-devise/config/application.rb",
    "test/dummy-with-devise/config/boot.rb",
    "test/dummy-with-devise/config/database.yml",
    "test/dummy-with-devise/config/environment.rb",
    "test/dummy-with-devise/config/environments/development.rb",
    "test/dummy-with-devise/config/environments/production.rb",
    "test/dummy-with-devise/config/environments/test.rb",
    "test/dummy-with-devise/config/initializers/backtrace_silencers.rb",
    "test/dummy-with-devise/config/initializers/devise.rb",
    "test/dummy-with-devise/config/initializers/inflections.rb",
    "test/dummy-with-devise/config/initializers/mime_types.rb",
    "test/dummy-with-devise/config/initializers/secret_token.rb",
    "test/dummy-with-devise/config/initializers/session_store.rb",
    "test/dummy-with-devise/config/initializers/wrap_parameters.rb",
    "test/dummy-with-devise/config/locales/devise.en.yml",
    "test/dummy-with-devise/config/locales/en.yml",
    "test/dummy-with-devise/config/routes.rb",
    "test/dummy-with-devise/db/migrate/20111110074559_devise_create_users.rb",
    "test/dummy-with-devise/db/schema.rb",
    "test/dummy-with-devise/db/seeds.rb",
    "test/dummy-with-devise/lib/assets/.gitkeep",
    "test/dummy-with-devise/lib/tasks/.gitkeep",
    "test/dummy-with-devise/log/.gitkeep",
    "test/dummy-with-devise/public/404.html",
    "test/dummy-with-devise/public/422.html",
    "test/dummy-with-devise/public/500.html",
    "test/dummy-with-devise/public/favicon.ico",
    "test/dummy-with-devise/public/robots.txt",
    "test/dummy-with-devise/script/rails",
    "test/dummy-with-devise/test/fixtures/.gitkeep",
    "test/dummy-with-devise/test/fixtures/users.yml",
    "test/dummy-with-devise/test/functional/.gitkeep",
    "test/dummy-with-devise/test/functional/home_controller_test.rb",
    "test/dummy-with-devise/test/integration/.gitkeep",
    "test/dummy-with-devise/test/performance/browsing_test.rb",
    "test/dummy-with-devise/test/test_helper.rb",
    "test/dummy-with-devise/test/unit/.gitkeep",
    "test/dummy-with-devise/test/unit/helpers/home_helper_test.rb",
    "test/dummy-with-devise/test/unit/user_test.rb",
    "test/dummy-with-devise/vendor/assets/stylesheets/.gitkeep",
    "test/dummy-with-devise/vendor/plugins/.gitkeep",
    "test/dummy/.gitignore",
    "test/dummy/Gemfile",
    "test/dummy/Gemfile.lock",
    "test/dummy/README",
    "test/dummy/Rakefile",
    "test/dummy/app/assets/images/rails.png",
    "test/dummy/app/assets/javascripts/application.js",
    "test/dummy/app/assets/javascripts/posts.js.coffee",
    "test/dummy/app/assets/stylesheets/application.css",
    "test/dummy/app/assets/stylesheets/posts.css.scss",
    "test/dummy/app/assets/stylesheets/scaffolds.css.scss",
    "test/dummy/app/controllers/application_controller.rb",
    "test/dummy/app/controllers/posts_controller.rb",
    "test/dummy/app/helpers/application_helper.rb",
    "test/dummy/app/helpers/posts_helper.rb",
    "test/dummy/app/mailers/.gitkeep",
    "test/dummy/app/models/.gitkeep",
    "test/dummy/app/models/post.rb",
    "test/dummy/app/views/layouts/application.html.erb",
    "test/dummy/app/views/posts/_form.html.erb",
    "test/dummy/app/views/posts/edit.html.erb",
    "test/dummy/app/views/posts/index.html.erb",
    "test/dummy/app/views/posts/new.html.erb",
    "test/dummy/app/views/posts/show.html.erb",
    "test/dummy/app/views/shared/_flash_messages.html.erb",
    "test/dummy/config.ru",
    "test/dummy/config/application.rb",
    "test/dummy/config/boot.rb",
    "test/dummy/config/database.yml",
    "test/dummy/config/environment.rb",
    "test/dummy/config/environments/development.rb",
    "test/dummy/config/environments/production.rb",
    "test/dummy/config/environments/test.rb",
    "test/dummy/config/initializers/backtrace_silencers.rb",
    "test/dummy/config/initializers/inflections.rb",
    "test/dummy/config/initializers/mime_types.rb",
    "test/dummy/config/initializers/secret_token.rb",
    "test/dummy/config/initializers/session_store.rb",
    "test/dummy/config/initializers/wrap_parameters.rb",
    "test/dummy/config/locales/en.yml",
    "test/dummy/config/routes.rb",
    "test/dummy/db/migrate/20111105100343_create_posts.rb",
    "test/dummy/db/schema.rb",
    "test/dummy/db/seeds.rb",
    "test/dummy/lib/assets/.gitkeep",
    "test/dummy/lib/tasks/.gitkeep",
    "test/dummy/log/.gitkeep",
    "test/dummy/public/404.html",
    "test/dummy/public/422.html",
    "test/dummy/public/500.html",
    "test/dummy/public/favicon.ico",
    "test/dummy/public/index.html",
    "test/dummy/public/robots.txt",
    "test/dummy/script/rails",
    "test/dummy/test/fixtures/.gitkeep",
    "test/dummy/test/fixtures/posts.yml",
    "test/dummy/test/functional/.gitkeep",
    "test/dummy/test/functional/posts_controller_test.rb",
    "test/dummy/test/integration/.gitkeep",
    "test/dummy/test/performance/browsing_test.rb",
    "test/dummy/test/test_helper.rb",
    "test/dummy/test/unit/.gitkeep",
    "test/dummy/test/unit/helpers/posts_helper_test.rb",
    "test/dummy/test/unit/post_test.rb",
    "test/dummy/vendor/assets/stylesheets/.gitkeep",
    "test/dummy/vendor/plugins/.gitkeep",
    "test/helper.rb",
    "test/test_flushing-flash.rb"
  ]
  s.homepage = %q{http://github.com/peterwongpp/flushing-flash}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{To provide helper methods for handling rails flash messages.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

